version: '3'
services:
  app:
    image: site_init
    ports:
      - "3000:3000"  # Mapeia a porta 3000 do container para a porta 3000 do host
    networks:
      - npm_public

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - npm_public

networks:
  npm_public: